# Generated by Django 4.2.1 on 2023-05-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_category_options_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("ordering",), "verbose_name": "Category"},
        ),
        migrations.AddField(
            model_name="category",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
    ]
